---

- name: Create swapfile
  command: fallocate -l 1024m {{ swapfile_path }} creates={{ swapfile_path }}

- name: Set swapfile permissions
  file: path={{ swapfile_path }} owner=root group=root mode=0600

- name: Format swapfile
  command: mkswap {{ swapfile_path }}

- name: Add swapfile to fstab
  mount: 
    src={{ swapfile_path }}
    fstype=swap
    name=none
    opts=sw
    passno=0
    dump=0
    state=present

- name: Mount swap
  command: swapon {{ swapfile_path }} 
