---

- name: Add Ansible PPA
  apt_repository: 
    repo: 'ppa:ansible/ansible'
    state: present

- name: "Install Ansible"
  apt: 
    pkg: ansible 
    state: present
    update_cache: yes

- name: Remove Ansible PPA (clean up)
  apt_repository: 
    repo: 'ppa:ansible/ansible'
    state: absent
