---

- name: Clean out /var/www
  file: path=/var/www/html state=absent
  
- name: Remove unneeded software
  apt: name={{ item }} state=absent purge=yes
  with_items: 
    - apt-xapian-index
    - bash-completion
    - chef
    - puppet
    - vim-common
    - x11-common

- name: Thin unused files and directories
  file: path={{ item }} state=absent
  with_items:
    - /usr/share/bash-completion
    - /usr/share/groff
    - /usr/share/info
    - /usr/share/locale
    - /usr/share/man
    - /usr/share/vim
    - /usr/share/X11
    - /var/cache/apt-xapian-index
    - /var/cache/chef
    - /var/cache/man

# Something in the VirtualBox Guest Additions requires some unknown directory in
# /usr/share/doc. Shared folders will fail to mount without it. So, we can remove
# all the files to shrink the disk image, but we can't remove the empty directories
- name: Remove all files from /usr/share/doc
  shell: find /usr/share/doc -type f -delete

- name: Remove apt leftovers and orphans
  shell: apt-get autoremove -y

- name: Clear the apt cache
  shell: apt-get clean -y
