---

- name: Clean out /var/www
  file: path=/var/www/html state=absent
  
- name: Remove unneeded software
  apt: name={{ item }} state=absent purge=yes
  with_items: 
    - apt-xapian-index
    - bash-completion
    - chef
    - puppet
    - vim-common
    - x11-common
    - poppler-data
    - netcat-openbsd
    - tasksel

# This triggers a deprecation warning, but I couldn't get Ansible's
# v2.1 module syntax to run without failing with this Module Error:
#     TypeError: 'NoneType' object is not iterable
# http://docs.ansible.com/ansible/apt_module.html#options
- name: Remove apt leftovers and orphans (apt-get autoremove -y)
  shell: apt-get autoremove -y

- name: Thin unused files and directories in /usr/share
  file: path={{ item }} state=absent
  with_items:
    - /usr/share/bash-completion
    - /usr/share/groff
    - /usr/share/info
    - /usr/share/locale
    - /usr/share/man
    - /usr/share/lintian
    - /usr/share/vim
    - /usr/share/X11    
    
# Something in the VirtualBox Guest Additions requires some unknown directory in
# /usr/share/doc. Shared folders will fail to mount without it. So, we can remove
# all the files to shrink the disk image, but we can't remove the empty directories
- name: Remove all files from /usr/share/doc
  shell: find /usr/share/doc -type f -delete

- name: Collect caches
  shell: ls -1 /var/cache
  register: cache

- name: Empty /var/cache
  file: 
    path=/var/cache/{{ item }}
    state=absent
  with_items: '{{ cache.stdout_lines }}'

- name: Collect apt lists
  shell: ls -1 /var/lib/apt/lists/
  register: var_lib_apt

- name: Clean out /var/lib/apt/lists
  file:
    path: '/var/lib/apt/lists/{{ item }}'
    state: absent
  with_items: '{{ var_lib_apt.stdout_lines }}'

- name: Remove all /usr/**/*.pyc files
  shell: find /usr -name *.pyc -delete