---

- name: Install Python MySQL library
  apt: name=python-mysqldb update_cache=yes

- name: install MySQL-server 
  apt: name=mysql-server

- set_fact:
    mysql_root_password: "password"

- service: name=mysql state=started

- name: update mysql root password for all root accounts
  mysql_user: 'name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT'
  with_items:  
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest="{{ item.path }}/.my.cnf" owner={{ item.user }} group={{ item.user }} mode=0600
  with_items: 
    - {path: /root, user: root}
    - {path: /home/vagrant, user: vagrant}

- name: remove the MySQL test database
  mysql_db:
    db=test
    state=absent
