---

- name: "Install PHP 5 Debugging Tools"
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - php5-xdebug

- name: Write error reporting INI
  copy:
    src=error_reporting_all.ini
    dest=/etc/php5/mods-available/error_reporting.ini
    mode=0644

- name: Enable PHP error reporting INI
  command: php5enmod error_reporting
  notify:
    - restart apache
