---

- name: Add Ondřej Surý's PHP ppa https://launchpad.net/~ondrej
  apt_repository: 
    repo: 'ppa:ondrej/php'

- name: "Install PHP Debugging Tools"
  apt: 
    pkg:
        - php-xdebug
    state: present 
    update_cache: yes

- name: Write error reporting INI
  copy:
    src: error_reporting_all.ini
    dest: /etc/php/{{ php_version }}/mods-available/error_reporting.ini
    mode: 0644

- name: Enable PHP error reporting INI
  command: phpenmod error_reporting
  notify:
    - restart apache

- name: Remove php repo (clean up)
  apt_repository: 
    repo: 'ppa:ondrej/php'
    state: absent
