---

- name: Select PHP version https://launchpad.net/~ondrej
  set_fact: 
    # php5_ppa: 'ppa:ondrej/php5-oldstable' # php 5.4.x
    # php_ppa: 'ppa:ondrej/php5'            # PHP 5.5.x
    # php_ppa: 'ppa:ondrej/php5-5.6'        # PHP 5.6.x
    php_ppa: 'ppa:ondrej/php-7.0'           # PHP 7.0.x

- name: Add Ondřej Surý's PHP ppa
  apt_repository: repo={{ php_ppa }}
  
- name: "Install PHP 5"
  apt: pkg={{ item }} state=installed update_cache=yes
  when: "'php5' in php_ppa"
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php5-xmlrpc
    - php5-gd

- name: "Install PHP 7"
  apt: pkg={{ item }} state=installed update_cache=yes
  when: "'php5' not in php_ppa"
  with_items:
    - php7.0
    - php7.0-cli
    - php7.0-curl
    - php7.0-mysql
    - php7.0-mcrypt
    - php7.0-gd
    # - php7.0-xmlrpc  # now built in with PHP7?

- set_fact:
    php_dirname: "{{ ('php5' in php_ppa) | ternary('php5', 'php') }}"
  
- name: Write INI for default time zone
  template: src=timezone.ini.j2 dest=/etc/{{ php_dirname }}/mods-available/timezone.ini

- name: Generate error reporting INI -- no errors
  template: src=error_reporting_none.ini.j2 dest=/etc/{{ php_dirname }}/mods-available/error_reporting.ini

- name: Set upload_max_filesize
  template: src=upload_max_filesize.ini.j2 dest=/etc/{{ php_dirname }}/mods-available/upload_max_filesize.ini

- name: Set max_execution_time
  template: src=max_execution_time.ini.j2 dest=/etc/{{ php_dirname }}/mods-available/max_execution_time.ini

- name: Enable Mod INIs
  command: "{{ ('php5' in php_ppa) | ternary('php5enmod', 'phpenmod') }} {{ item }}"
  with_items: 
    - mcrypt
    - timezone
    - error_reporting
    - upload_max_filesize
    - max_execution_time
    - xmlrpc
    - gd

- name: Remove php ppa repo (clean up)
  apt_repository: repo={{ php_ppa }} state=absent
