---

- name: Select PHP version https://launchpad.net/~ondrej
  set_fact:
    # php5_ppa: 'ppa:ondrej/php5-oldstable' # php 5.4.x
    php5_ppa: 'ppa:ondrej/php5'             # PHP 5.5.x
    # php5_ppa: 'ppa:ondrej/php5-5.6'       # PHP 5.6.x

- name: Add Ondřej Surý's PHP ppa
  apt_repository: repo={{ php5_ppa }}

- name: "Install PHP 5"
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php5-xmlrpc
    - php5-gd

- name: Write INI for default time zone
  template: src=timezone.ini.j2 dest=/etc/php5/mods-available/timezone.ini

- name: Generate error reporting INI -- no errors
  template: src=error_reporting_none.ini.j2 dest=/etc/php5/mods-available/error_reporting.ini

- name: Set upload_max_filesize
  template: src=upload_max_filesize.ini.j2 dest=/etc/php5/mods-available/upload_max_filesize.ini

- name: Set max_execution_time
  template: src=max_execution_time.ini.j2 dest=/etc/php5/mods-available/max_execution_time.ini

- name: Enable Mod INIs
  command: php5enmod {{ item }}
  with_items:
    - mcrypt
    - timezone
    - error_reporting
    - upload_max_filesize
    - max_execution_time
    - xmlrpc
    - gd

- name: Remove php5 repo (clean up)
  apt_repository: repo={{ php5_ppa }} state=absent

# - name: Enable Apache2 PHP module
#   command: a2enmod {{ item }}
#   with_items:
#     - php5
  # notify:
  #   - restart apache
