---

  - name: Add Git PPA
    apt_repository:
      repo: 'ppa:git-core/ppa'

  - name: install Git
    apt:
      pkg: git
      state: present
      update_cache: yes

  - name: Remove Git repo (clean up)
    apt_repository:
      repo: 'ppa:git-core/ppa'
      state: absent
