---

- hosts: all
  become: yes

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Ansible version check
      fail:
        msg: This playbook requires an Ansible version greater than 2.2 for the unarchive module to work correctly.
      when: ansible_version.full | version_compare('2.2.0', '<')

    - name: Disable apt's cache
      copy:
        content='Dir::Cache { srcpkgcache ""; pkgcache ""; }'
        dest=/etc/apt/apt.conf.d/02nocache

    - name: install python-software-properties (required for apt-add-repository)
      apt: pkg=python-software-properties state=installed update_cache=yes

    - name: install unzip (for local provisioning on the VM)
      apt:
        pkg=unzip
        state=installed

    - name: Add vagrant user to www-data group
      user:
        name=vagrant
        groups=www-data
        append=yes

    - name: Add www-data user to vagrant group ¯\_(ツ)_/¯
      user:
        name=www-data
        groups=vagrant
        append=yes

  roles: 
    - swapfile
    - virtualbox
    - { role: apache, site_root: '/var/www/wordpress', document_root: '/var/www/wordpress', site_name: basic-wp }
    - ansible
    - php
    - mysql
    - wp-cli
    - clean_ubuntu
    
  post_tasks:
    - name: Setup default wordpress symlink
      file: 
        state=link
        src=/vagrant/site
        dest=/var/www/wordpress
        force=yes
        owner=www-data 
        group=www-data
    
    - name: Create default WordPress MySQL user
      mysql_user: 'name={{ wp_config.db_user }} password={{ wp_config.db_password }} priv=*.*:ALL state=present'

    - name: Create a new Database
      mysql_db: name={{ wp_config.db_name }} state=present
