---

- hosts: all
  sudo: yes

  vars_files:
    - defaults/main.yml

  pre_tasks:     
    - name: install python-software-properties (required for apt-add-repository)
      apt: pkg=python-software-properties state=installed update_cache=yes
      
    - set_fact: 
        swapfile_path: /mnt/1024MiB.swap

    - name: Create swapfile
      command: fallocate -l 1024m {{ swapfile_path }} creates={{ swapfile_path }}
    
    - file: path={{ swapfile_path }} owner=root group=root mode=0600

    - name: Mount swap
      command: swapon {{ swapfile_path }} 
      
    - name: Add swapfile to fstab
      mount: 
        src={{ swapfile_path }}
        fstype=swap
        name=none
        opts=sw
        passno=0
        dump=0
        state=present

  roles: 
    - mysql
    - php
    - php5-xdebug
    - { role: apache, site_root: '/var/www/wordpress', document_root: '/var/www/wordpress' }
    
  post_tasks:
    
    - name: Create default WordPress MySQL user
      mysql_user: 'name={{ wp_config.db_user }} password={{ wp_config.db_password }} priv=*.*:ALL state=present'

    - name: Create a new Database
      mysql_db: name={{ wp_config.db_name }} state=present
