---

- hosts: all
  sudo: yes

  tasks: 
    - debug: "hello"
    
    - name: install python-software-properties (required for apt-add-repository)
      apt: pkg=python-software-properties state=installed update_cache=yes
      
  roles: 
    - mysql
    - php
    - php5-xdebug