---

- name: Download and install wp-cli.phar
  get_url:
    url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest=/usr/local/bin/wp
    force=yes

- name: set wp-cli permissions
  file:
    path=/usr/local/bin/wp
    mode=0755

- name: Make sure ~/wp-cli directory exists
  file:
    path=/home/vagrant/.wp-cli
    state=directory
    owner=www-data
    group=www-data
    mode=0755

- name: Write ~/.wp-cli/config.yml file
  template: 
    src=config.yml.j2 
    dest=/home/vagrant/.wp-cli/config.yml
    mode=755
